name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  prerelease:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.prerelease.outputs.upload_url }}
    steps:
      - name: Get version from tag
        id: tagname
        run: |
          echo "name=current_version::${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create release
        id: prerelease
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOCI }}
        with:
          tag_name: ${{ steps.tagname.outputs.current_version }}
          release_name: ${{ steps.tagname.outputs.current_version }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: false

  build:
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Install pkg
        run: npm install -g pkg
      - name: Create package
        run: npm run pkg
      - name: Create dir
        run: mkdir input
      - name: Make zip file
        run: zip ./muzinstock-${{ steps.tagname.outputs.current_version }}.zip muzinstock.exe input
        shell: bash

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOCI }}
        with:
          upload_url: ${{ steps.prerelease.outputs.upload_url }}
          asset_path: ./muzinstock-${{ steps.tagname.outputs.current_version }}.zip
          asset_name: muzinstock-${{ steps.tagname.outputs.current_version }}.zip
          asset_content_type: application/zip
