name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Install pkg
        run: npm install -g pkg
      - name: Create package
        run: npm run pkg
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.step_version.outputs.version }}
          upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
      - id: step_version
        run: echo "::set-output name=version::${{ steps.package_version.outputs.version }}"
      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
