name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Install pkg
        run: npm install -g pkg
      - name: Create package
        run: npm run pkg
      - name: Create dir
        run: mkdir input
      - name: Make zip file
        run: zip -r ./muzinstock.zip .
        shell: bash
