name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: tagname
        run: |
          echo "name=current_version::${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Create package
        run: npm run pkg

      - name: Make a zip
        run: |
          mkdir input
          zip -r muzinstock-${{ steps.tagname.outputs.current_version }}.zip muzinstock.exe input

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOCI }}
        with:
          tag_name: ${{ steps.tagname.outputs.current_version }}
          release_name: ${{ steps.tagname.outputs.current_version }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: false

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOCI }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./muzinstock-${{ steps.tagname.outputs.current_version }}.zip
          asset_name: muzinstock-${{ steps.tagname.outputs.current_version }}.zip
          asset_content_type: application/zip
