name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 모듈 설치
      - name: Install modules
        run: npm install
      # pkg 명령
      - name: Create package
        run: npm run pkg
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1.2
          release_name: v1.1.2
